sonar.host.url=https://sonarcloud.io
sonar.token=db4e2dd3dee6199a443b3578b02fd095260091b0



sonar.projectKey=nandu1231239_task-manager-api

sonar.organization=nandu1231239
sonar.projectName=Task Manager API
sonar.projectVersion=1.0.0



sonar.sources=src
sonar.tests=tests
sonar.exclusions=node_modules/**, tests/**
sonar.test.inclusions=tests/**/*.test.js
sonar.sourceEncoding=UTF-8
